config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :users, only: [ :index, :show] do
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  belongs_to :post, foreign_key: :post_id

  after_save :update_comments_counter
  after_destroy :decrement_comments_counter

  def update_comments_counter
    post.increment!(:commentsCounter)
  end

  def decrement_comments_counter
    post.decrement!(:commentsCounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  belongs_to :post, foreign_key: :post_id

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id
  after_save :update_posts_counter
  after_destroy :decrement_posts_counter

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :text, presence: true, length: { minimum: 3, maximum: 1000 }
  validates :commentsCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_posts_counter
    author.increment!(:postsCounter)
  end

  def decrement_posts_counter
    author.decrement!(:postsCounter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, length: { maximum: 100 }
  validates :postsCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    @comments = Comment.all.where(author_id: params.require(:user_id), post_id: params.require(:post_id))
    render json: @comments
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      render json: @comment, status: :created, location: @comment
    else
      render json: { error: 'Comment not saved' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.all.where(author_id: params.require(:user_id))
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :error, :success
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?
  include CanCan::ControllerAdditions

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find_by(id: params[:post_id])
    @comment = Comment.new(post:, author: current_user, text: comment_params[:text])
    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(post_id: params[:post_id], author_id: current_user.id)
    if @like.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:sucess] = 'Post created successfully'
      redirect_to user_posts_path(params[:user_id])
    else
      flash[:error] = 'Post not created'
      render :new
    end
  end

  def index
    @posts = Post.where(author_id: params[:user_id]).order(created_at: :desc)
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @post = Post.find_by(author_id: params[:user_id], id: params[:id]) || 'No posts yet'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    redirect_to user_posts_path(params[:user_id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(author_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id]) || 'User not found'
    @posts = @user.posts.order(created_at: :desc).limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div><%= render partial: "users/navBar" %></div>
<div class="addComment">
    <h1>Add new comment to the post </h1>
    <%= form_with model: @comment, url: user_post_comments_path, local: true do |form| %>
        <p>
            <%= form.label :text%><br>
            <%= form.text_area :text %>
        </p>
        <p>
            <%= form.submit %>
        </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

        <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div><%= render partial: "users/navBar" %></div>
<div class="user">
    <%= render partial: "users/user", locals: {user: @user} %>
    
</div>


<div class="postsContainer">    
    <% count = 1 %>
    <% @posts.each do |post| %>
        <a href=<%= "posts/#{post.id}" %> class="postLink">
            <div class="post">            
            <h3 class="postTitle">Post #<%= count %></h3>
            <p class="postText"><%= post.text %></p>
            <div class="counters">
                <p class="likesCounter">Likes: <%= post.likesCounter || 0 %></p>
                <p class="commentsCounter">Comments: <%= post.commentsCounter || 0 %></p>
            </div>
            <div class="commentsContainer">
                <% if post.comments.empty? %>
                    <p>No comments yet</p>
                <% else %>
                    <% post.recent_comments.each do |comment| %>
                        <div class="comment">
                            <p class="comment"><%= comment.author.name %> : <%= comment.text%></p>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
        </a>
        <% count += 1 %>
    <% end %>
    <button class="postsButton">
        <%= link_to "Create new post", new_user_post_path %>
    </button>
</div>

app/views/posts/new.html.erb
<div><%= render partial: "users/navBar" %></div>
<div class="formContainer">
  <h1>Add new post</h1>
  <div>
      <%= form_with model: @post, url: user_posts_path , local: true do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
      </p>
      <p>
        <%= form.submit 'Submit post' %>
      </p>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div><%= render partial: "users/navBar" %></div>
<div class="post">
    <h3 class="postTitle">Post#<%= @post.id %> by <%= @post.author.name %></h3>
    <div class="counters">
        <p class="likesCounter">Likes: <%= @post.likesCounter || 0 %></p>
        <p class="commentsCounter">Comments: <%= @post.commentsCounter || 0 %></p>
        <% if can? :destroy, @post %>
            <%= link_to "Delete post", user_post_path(@post.author.id, @post), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to delete this post?"
            } %>
        <% end %>
    </div>

    <p class="postText"><%= @post.text %></p>
    <div class="buttonContainer">
        <%=form_with model: @like, url: user_post_likes_path(@post.author.id, @post), local: true  do |form| %>
            <p>
                <%= form.submit "Add Like" %>
            </p>
        <% end %>
        <button class="buttons">
            <%= link_to "Add comment", new_user_post_comment_path(@post.author.id, @post) %>
        </button>
    </div>

    
</div>

<div class="commentsContainer">
<div class="comments">
    <% if @post.comments.empty? %>
        <p  class="comment">No comments yet</p>
    <% else %>        

        <% @post.comments.each do |comment| %>
                <p class="comment"><%= comment.author.name %> : <%= comment.text%></p>
                <% if can? :destroy, comment %>
                    <%= link_to "Delete comment", user_post_comment_path(@post.author.id, @post.id, comment.id), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to delete this comment?"
                    } %>
                <% end%>
        <% end %>                   

    <% end %>    
</div>
</div>

app/views/users/_navBar.html.erb
<nav class="navBar">
    <div class="navContainer">
        <%= link_to "Home", root_path, class: "navLink" %>
        <h2>Blog app</h2>
        <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navLink" %>
        <% else %>
            <%= link_to "Sign in", user_session_path, class: "navLink" %>
            <%= link_to "Sign up", new_user_registration_path, class: "navLink" %>
        <% end %>
    </div>
</nav>

app/views/users/_user.html.erb
<div class="user">
                <img src="<%= user.photo %>" alt="<%= user.name %>" class="userImg"/>  
                <div class="userDetails">      
                    <h2 class="userName"><%= user.name %></h2>
                    <p class="postCount">Number of posts: <%= user.postsCounter || 0 %></p>
                </div>
</div>

app/views/users/index.html.erb
<div><%= render partial: "navBar" %></div>
<div class="usersContainer">

    <% @users.each do |user| %>
        <a href="/users/<%= user.id %>" class="userLink">
            <%= render partial: "user", locals: {user: user} %>  
        </a>
    <% end %>  

</div>

app/views/users/show.html.erb
<div><%= render partial: "navBar" %></div>
<div class="user">
    <%= render partial: "user", locals: {user: @user} %>
</div>

<div class="bio">
    <h2 class="bioTitle">Bio</h2>
    <p class="bioText"><%= @user.bio %></p>
</div>

<div class="postsContianer">
    <% count = @user.postsCounter %>
    <% @user.recent_posts.each do |post| %>
        <div class="post">
            <h3 class="postTitle">Post#<%= count %></h3>
            <p class="postText"><%= post.text %></p>
            <div class="counters">
                <p class="likesCounter">Likes: <%= post.likesCounter || 0 %></p>
                <p class="commentsCounter">Comments: <%= post.commentsCounter || 0 %></p>
            </div>
        </div>  
        <% count -= 1 %>
    <% end %>
</div>


    <a href=<%= "#{@user.id}/posts"%> class="allPostsLink"><button class="allPostButton">See all posts</button></a>